import { Country } from './country';
import {ResearchStatus} from './status-enum';
export const COUNTRIES: Country[] = [
	{
        id: 1,
        title: "Quantum Computing Under Mechatronics",
        name: 'France',
		flag: 'c/c3/Flag_of_France.svg',
		area: 640679,
		population: 64979548,
        short_desc: "This research is expected to generate new form of energy",
        big_desc:"Quantum computing is an area of computer science focused on the development of technologies based on the principles of quantum theory. Quantum computing uses the unique behaviors of quantum physics to solve problems that are too complex for classical computing. Development of quantum computers marks a leap forward in computing capability, with the potential for massive performance gains in specific use cases. For example, quantum computing is expected to excel at tasks such as integer factorization and simulations and shows potential for use in industries such as pharmaceuticals, healthcare, manufacturing, cybersecurity and finance. According to industry trade publication The Quantum Insider, there are more than 600 companies and more than 30 national labs and government agencies worldwide that are developing quantum computing technology.  ",
        category: "Data Science",
        status:ResearchStatus.Ongoing,
        owner:"Peter Joy",
        cover_pic: "https://computing.utexas.edu/sites/default/files/2021-11/quantum-bits_fuller700.jpeg",
        supporting_pic_1: "https://s3.amazonaws.com/cms.ipressroom.com/173/files/20218/614914362cfac27230bd122e_Quantum+biology+center+personnel/Quantum+biology+center+personnel_mid.jpg",
        supporting_pic_2: "https://www.dtu.dk/english/-/media/dtudk/nyheder/webnyheder/2022/11/13884_dtu-danchip-800px_web.jpg?rw=960&rh=0&hash=9D8256B283579D5C03EFD84B3A788F7CADFEC314",
        supporting_pic_3: "https://science.ku.dk/forskning/kvanteforskning-paa-science/billedinformation/Pix_2_1100x600.jpg",
	},

    {
        id: 2,
        title: "Advanced UI/UX",
        name: 'Germany',
		flag: 'b/ba/Flag_of_Germany.svg',
		area: 357114,
        population: 36624199,
        short_desc: "This research is expected to generate new form of energy",
        big_desc:"After finding that energy is important we decided to invent new form of energy by using quantum computing",
        category: "Software Engineering",
        status:ResearchStatus.Completed,
        owner:"John Stewart",
        cover_pic: "https://uploads.sitepoint.com/wp-content/uploads/2020/02/1582544632screen-readers.png",
        supporting_pic_1: "https://s3.amazonaws.com/cms.ipressroom.com/173/files/20218/614914362cfac27230bd122e_Quantum+biology+center+personnel/Quantum+biology+center+personnel_mid.jpg",
        supporting_pic_2: "https://www.dtu.dk/english/-/media/dtudk/nyheder/webnyheder/2022/11/13884_dtu-danchip-800px_web.jpg?rw=960&rh=0&hash=9D8256B283579D5C03EFD84B3A788F7CADFEC314",
        supporting_pic_3: "https://science.ku.dk/forskning/kvanteforskning-paa-science/billedinformation/Pix_2_1100x600.jpg",
	},

    {
        id: 3,
        title: "IoT Protection using On-Host IDS",
        name: 'Canada',
		flag: 'c/cf/Flag_of_Canada.svg',
		area: 9976140,
		population: 36624199,
        short_desc: "This research is expected to generate new form of energy",
        big_desc:"Quantum computing is an area of computer science focused on the development of technologies based on the principles of quantum theory. Quantum computing uses the unique behaviors of quantum physics to solve problems that are too complex for classical computing. Development of quantum computers marks a leap forward in computing capability, with the potential for massive performance gains in specific use cases. For example, quantum computing is expected to excel at tasks such as integer factorization and simulations and shows potential for use in industries such as pharmaceuticals, healthcare, manufacturing, cybersecurity and finance. According to industry trade publication The Quantum Insider, there are more than 600 companies and more than 30 national labs and government agencies worldwide that are developing quantum computing technology.  ",
        category: "Cybersecurity",
        status:ResearchStatus.Published,
        owner:"Hanna Piercy",
        cover_pic: "https://learn.g2.com/hubfs/_Learn-IoT%20Security.png",
        supporting_pic_1: "https://s3.amazonaws.com/cms.ipressroom.com/173/files/20218/614914362cfac27230bd122e_Quantum+biology+center+personnel/Quantum+biology+center+personnel_mid.jpg",
        supporting_pic_2: "https://www.dtu.dk/english/-/media/dtudk/nyheder/webnyheder/2022/11/13884_dtu-danchip-800px_web.jpg?rw=960&rh=0&hash=9D8256B283579D5C03EFD84B3A788F7CADFEC314",
        supporting_pic_3: "https://science.ku.dk/forskning/kvanteforskning-paa-science/billedinformation/Pix_2_1100x600.jpg",
	},

    {
        id: 4,
        title: "Quantum Computing Under Mechatronics",
        name: 'Vietnam',
		flag: '2/21/Flag_of_Vietnam.svg',
		area: 331212,
		population: 95540800,
        short_desc: "This research is expected to generate new form of energy",
        big_desc:"After finding that energy is important we decided to invent new form of energy by using quantum computing",
        category: "Data Science",
        status:ResearchStatus.Ongoing,
        owner:"Peter Joy",
        cover_pic: "https://computing.utexas.edu/sites/default/files/2021-11/quantum-bits_fuller700.jpeg",
        supporting_pic_1: "https://s3.amazonaws.com/cms.ipressroom.com/173/files/20218/614914362cfac27230bd122e_Quantum+biology+center+personnel/Quantum+biology+center+personnel_mid.jpg",
        supporting_pic_2: "https://www.dtu.dk/english/-/media/dtudk/nyheder/webnyheder/2022/11/13884_dtu-danchip-800px_web.jpg?rw=960&rh=0&hash=9D8256B283579D5C03EFD84B3A788F7CADFEC314",
        supporting_pic_3: "https://science.ku.dk/forskning/kvanteforskning-paa-science/billedinformation/Pix_2_1100x600.jpg",
	},

    {
        id: 5,
        title: "Advanced UI/UX",
        name: 'Brazil',
		flag: '0/05/Flag_of_Brazil.svg',
		area: 8515767,
		population: 209288278,
        short_desc: "This research is expected to generate new form of energy",
        big_desc:"Quantum computing is an area of computer science focused on the development of technologies based on the principles of quantum theory. Quantum computing uses the unique behaviors of quantum physics to solve problems that are too complex for classical computing. Development of quantum computers marks a leap forward in computing capability, with the potential for massive performance gains in specific use cases. For example, quantum computing is expected to excel at tasks such as integer factorization and simulations and shows potential for use in industries such as pharmaceuticals, healthcare, manufacturing, cybersecurity and finance. According to industry trade publication The Quantum Insider, there are more than 600 companies and more than 30 national labs and government agencies worldwide that are developing quantum computing technology.  ",
        category: "Software Engineering",
        status:ResearchStatus.Review,
        owner:"John Stewart",
        cover_pic: "https://uploads.sitepoint.com/wp-content/uploads/2020/02/1582544632screen-readers.png",
        supporting_pic_1: "https://s3.amazonaws.com/cms.ipressroom.com/173/files/20218/614914362cfac27230bd122e_Quantum+biology+center+personnel/Quantum+biology+center+personnel_mid.jpg",
        supporting_pic_2: "https://www.dtu.dk/english/-/media/dtudk/nyheder/webnyheder/2022/11/13884_dtu-danchip-800px_web.jpg?rw=960&rh=0&hash=9D8256B283579D5C03EFD84B3A788F7CADFEC314",
        supporting_pic_3: "https://science.ku.dk/forskning/kvanteforskning-paa-science/billedinformation/Pix_2_1100x600.jpg",
	},

    {
        id: 6,
        title: "IoT Protection using On-Host IDS",
        name: 'Mexico',
		flag: 'f/fc/Flag_of_Mexico.svg',
		area: 1964375,
		population: 129163276,
        short_desc: "This research is expected to generate new form of energy",
        big_desc:"After finding that energy is important we decided to invent new form of energy by using quantum computing",
        category: "Cybersecurity",
        status:ResearchStatus.Completed,
        owner:"Hanna Piercy",
        cover_pic: "https://learn.g2.com/hubfs/_Learn-IoT%20Security.png",
        supporting_pic_1: "https://s3.amazonaws.com/cms.ipressroom.com/173/files/20218/614914362cfac27230bd122e_Quantum+biology+center+personnel/Quantum+biology+center+personnel_mid.jpg",
        supporting_pic_2: "https://www.dtu.dk/english/-/media/dtudk/nyheder/webnyheder/2022/11/13884_dtu-danchip-800px_web.jpg?rw=960&rh=0&hash=9D8256B283579D5C03EFD84B3A788F7CADFEC314",
        supporting_pic_3: "https://science.ku.dk/forskning/kvanteforskning-paa-science/billedinformation/Pix_2_1100x600.jpg",
	},

    {
        id: 7,
        title: "Quantum Computing Under Mechatronics",
        name: 'United States',
		flag: 'a/a4/Flag_of_the_United_States.svg',
		area: 9629091,
		population: 324459463,
        short_desc: "This research is expected to generate new form of energy",
       big_desc:"Quantum computing is an area of computer science focused on the development of technologies based on the principles of quantum theory. Quantum computing uses the unique behaviors of quantum physics to solve problems that are too complex for classical computing. Development of quantum computers marks a leap forward in computing capability, with the potential for massive performance gains in specific use cases. For example, quantum computing is expected to excel at tasks such as integer factorization and simulations and shows potential for use in industries such as pharmaceuticals, healthcare, manufacturing, cybersecurity and finance. According to industry trade publication The Quantum Insider, there are more than 600 companies and more than 30 national labs and government agencies worldwide that are developing quantum computing technology. This includes U.S.-based tech giants such as Amazon, Google, Hewlett Packard Enterprise, Hitachi, IBM, Intel and Microsoft as well as Massachusetts Institute of Technology, Oxford University and the Los Alamos National Laboratory. Other countries, including the U.K., Australia, Canada, China, Germany, Israel, Japan and Russia, have made significant investments in quantum computing technologies. The U.K. recently launched a government-funded quantum computing program. In 2020, the Indian government introduced its National Mission on Quantum Technologies & Applications. The global quantum computing market in 2021 was valued at $395 million USD, according to the report \"Quantum Computing Market\" from Markets N Research. The report predicts that the market will grow to approximately $532 million USD by 2028. Although quantum computing is a rapidly emerging technology, it has the potential to be a disruptive technology once it reaches maturity. Quantum computing companies are popping up all over the world, but experts estimate that it could take years before quantum computing delivers practical benefits. The first commercially available quantum computer was released in 2011 by D-Wave Systems. In 2019, IBM released the Quantum System One, and in November 2022, it unveiled the largest quantum computer yet, Osprey. Although the idea of using a quantum computer can be exciting, it's unlikely that most organizations will build or buy one. Instead, they might opt to use cloud-based services that enable remote access. For example, Amazon Braket, Microsoft Azure Quantum and Rigetti Quantum Cloud Services all provide quantum computing as a service. Commercial quantum computers are available anywhere from $5,000 to $15 million, depending on the processing power. For example, a quantum computer with 50 qbits can cost up to $10 million.",
        category: "Data Science",
        status:ResearchStatus.Recruiting,
        owner:"Peter Joy",
        cover_pic: "https://computing.utexas.edu/sites/default/files/2021-11/quantum-bits_fuller700.jpeg",
        supporting_pic_1: "https://s3.amazonaws.com/cms.ipressroom.com/173/files/20218/614914362cfac27230bd122e_Quantum+biology+center+personnel/Quantum+biology+center+personnel_mid.jpg",
        supporting_pic_2: "https://www.dtu.dk/english/-/media/dtudk/nyheder/webnyheder/2022/11/13884_dtu-danchip-800px_web.jpg?rw=960&rh=0&hash=9D8256B283579D5C03EFD84B3A788F7CADFEC314",
        supporting_pic_3: "https://science.ku.dk/forskning/kvanteforskning-paa-science/billedinformation/Pix_2_1100x600.jpg",
	},

    {
        id: 8,
        title: "Advanced UI/UX",
        name: 'India',
		flag: '4/41/Flag_of_India.svg',
		area: 3287263,
		population: 1324171354,
        short_desc: "This research is expected to generate new form of energy",
        big_desc:"Quantum computing is an area of computer science focused on the development of technologies based on the principles of quantum theory. Quantum computing uses the unique behaviors of quantum physics to solve problems that are too complex for classical computing. Development of quantum computers marks a leap forward in computing capability, with the potential for massive performance gains in specific use cases. For example, quantum computing is expected to excel at tasks such as integer factorization and simulations and shows potential for use in industries such as pharmaceuticals, healthcare, manufacturing, cybersecurity and finance. According to industry trade publication The Quantum Insider, there are more than 600 companies and more than 30 national labs and government agencies worldwide that are developing quantum computing technology.  ",
        category: "Software Engineering",
        status:ResearchStatus.Completed,
        owner:"John Stewart",
        cover_pic: "https://uploads.sitepoint.com/wp-content/uploads/2020/02/1582544632screen-readers.png",
        supporting_pic_1: "https://s3.amazonaws.com/cms.ipressroom.com/173/files/20218/614914362cfac27230bd122e_Quantum+biology+center+personnel/Quantum+biology+center+personnel_mid.jpg",
        supporting_pic_2: "https://www.dtu.dk/english/-/media/dtudk/nyheder/webnyheder/2022/11/13884_dtu-danchip-800px_web.jpg?rw=960&rh=0&hash=9D8256B283579D5C03EFD84B3A788F7CADFEC314",
        supporting_pic_3: "https://science.ku.dk/forskning/kvanteforskning-paa-science/billedinformation/Pix_2_1100x600.jpg",
	},

    {
        id: 9,
        title: "IoT Protection using On-Host IDS",
        name: 'Indonesia',
		flag: '9/9f/Flag_of_Indonesia.svg',
		area: 1910931,
		population: 263991379,
        short_desc: "This research is expected to generate new form of energy",
        big_desc:"After finding that energy is important we decided to invent new form of energy by using quantum computing",
        category: "Cybersecurity",
        status:ResearchStatus.Review,
        owner:"Hanna Piercy",
        cover_pic: "https://learn.g2.com/hubfs/_Learn-IoT%20Security.png",
        supporting_pic_1: "https://s3.amazonaws.com/cms.ipressroom.com/173/files/20218/614914362cfac27230bd122e_Quantum+biology+center+personnel/Quantum+biology+center+personnel_mid.jpg",
        supporting_pic_2: "https://www.dtu.dk/english/-/media/dtudk/nyheder/webnyheder/2022/11/13884_dtu-danchip-800px_web.jpg?rw=960&rh=0&hash=9D8256B283579D5C03EFD84B3A788F7CADFEC314",
        supporting_pic_3: "https://science.ku.dk/forskning/kvanteforskning-paa-science/billedinformation/Pix_2_1100x600.jpg",
	},

    {
        id: 10,
        title: "Quantum Computing Under Mechatronics",
        name: 'Tuvalu',
		flag: '3/38/Flag_of_Tuvalu.svg',
		area: 26,
		population: 11097,
        short_desc: "This research is expected to generate new form of energy",
        big_desc:"Quantum computing is an area of computer science focused on the development of technologies based on the principles of quantum theory. Quantum computing uses the unique behaviors of quantum physics to solve problems that are too complex for classical computing. Development of quantum computers marks a leap forward in computing capability, with the potential for massive performance gains in specific use cases. For example, quantum computing is expected to excel at tasks such as integer factorization and simulations and shows potential for use in industries such as pharmaceuticals, healthcare, manufacturing, cybersecurity and finance. According to industry trade publication The Quantum Insider, there are more than 600 companies and more than 30 national labs and government agencies worldwide that are developing quantum computing technology.  ",
        category: "Data Science",
        status:ResearchStatus.Ongoing,
        owner:"Peter Joy",
        cover_pic: "https://computing.utexas.edu/sites/default/files/2021-11/quantum-bits_fuller700.jpeg",
        supporting_pic_1: "https://s3.amazonaws.com/cms.ipressroom.com/173/files/20218/614914362cfac27230bd122e_Quantum+biology+center+personnel/Quantum+biology+center+personnel_mid.jpg",
        supporting_pic_2: "https://www.dtu.dk/english/-/media/dtudk/nyheder/webnyheder/2022/11/13884_dtu-danchip-800px_web.jpg?rw=960&rh=0&hash=9D8256B283579D5C03EFD84B3A788F7CADFEC314",
        supporting_pic_3: "https://science.ku.dk/forskning/kvanteforskning-paa-science/billedinformation/Pix_2_1100x600.jpg",
	},

    {
        id: 11,
        title: "Advanced UI/UX",
        name: 'China',
		flag: 'f/fa/Flag_of_the_People%27s_Republic_of_China.svg',
		area: 9596960,
		population: 1409517397,
        short_desc: "This research is expected to generate new form of energy",
        big_desc:"Quantum computing is an area of computer science focused on the development of technologies based on the principles of quantum theory. Quantum computing uses the unique behaviors of quantum physics to solve problems that are too complex for classical computing. Development of quantum computers marks a leap forward in computing capability, with the potential for massive performance gains in specific use cases. For example, quantum computing is expected to excel at tasks such as integer factorization and simulations and shows potential for use in industries such as pharmaceuticals, healthcare, manufacturing, cybersecurity and finance. According to industry trade publication The Quantum Insider, there are more than 600 companies and more than 30 national labs and government agencies worldwide that are developing quantum computing technology. This includes U.S.-based tech giants such as Amazon, Google, Hewlett Packard Enterprise, Hitachi, IBM, Intel and Microsoft as well as Massachusetts Institute of Technology, Oxford University and the Los Alamos National Laboratory. Other countries, including the U.K., Australia, Canada, China, Germany, Israel, Japan and Russia, have made significant investments in quantum computing technologies. The U.K. recently launched a government-funded quantum computing program. In 2020, the Indian government introduced its National Mission on Quantum Technologies & Applications. The global quantum computing market in 2021 was valued at $395 million USD, according to the report \"Quantum Computing Market\" from Markets N Research. The report predicts that the market will grow to approximately $532 million USD by 2028. Although quantum computing is a rapidly emerging technology, it has the potential to be a disruptive technology once it reaches maturity. Quantum computing companies are popping up all over the world, but experts estimate that it could take years before quantum computing delivers practical benefits. The first commercially available quantum computer was released in 2011 by D-Wave Systems. In 2019, IBM released the Quantum System One, and in November 2022, it unveiled the largest quantum computer yet, Osprey. Although the idea of using a quantum computer can be exciting, it's unlikely that most organizations will build or buy one. Instead, they might opt to use cloud-based services that enable remote access. For example, Amazon Braket, Microsoft Azure Quantum and Rigetti Quantum Cloud Services all provide quantum computing as a service. Commercial quantum computers are available anywhere from $5,000 to $15 million, depending on the processing power. For example, a quantum computer with 50 qbits can cost up to $10 million.",
        category: "Software Engineering",
        status:ResearchStatus.Completed,
        owner:"John Stewart",
        cover_pic: "https://uploads.sitepoint.com/wp-content/uploads/2020/02/1582544632screen-readers.png",
        supporting_pic_1: "https://s3.amazonaws.com/cms.ipressroom.com/173/files/20218/614914362cfac27230bd122e_Quantum+biology+center+personnel/Quantum+biology+center+personnel_mid.jpg",
        supporting_pic_2: "https://www.dtu.dk/english/-/media/dtudk/nyheder/webnyheder/2022/11/13884_dtu-danchip-800px_web.jpg?rw=960&rh=0&hash=9D8256B283579D5C03EFD84B3A788F7CADFEC314",
        supporting_pic_3: "https://science.ku.dk/forskning/kvanteforskning-paa-science/billedinformation/Pix_2_1100x600.jpg",
	},

    {
        id: 12,
        title: "IoT Protection using On-Host IDS",
        name: 'Russia',
		flag: 'f/f3/Flag_of_Russia.svg',
		area: 17075200,
		population: 146989754,
        short_desc: "This research is expected to generate new form of energy",
        big_desc:"Quantum computing is an area of computer science focused on the development of technologies based on the principles of quantum theory. Quantum computing uses the unique behaviors of quantum physics to solve problems that are too complex for classical computing. Development of quantum computers marks a leap forward in computing capability, with the potential for massive performance gains in specific use cases. For example, quantum computing is expected to excel at tasks such as integer factorization and simulations and shows potential for use in industries such as pharmaceuticals, healthcare, manufacturing, cybersecurity and finance. According to industry trade publication The Quantum Insider, there are more than 600 companies and more than 30 national labs and government agencies worldwide that are developing quantum computing technology.  ",
        category: "Cybersecurity",
        status:ResearchStatus.Recruiting,
        owner:"Hanna Piercy",
        cover_pic: "https://learn.g2.com/hubfs/_Learn-IoT%20Security.png",
        supporting_pic_1: "https://s3.amazonaws.com/cms.ipressroom.com/173/files/20218/614914362cfac27230bd122e_Quantum+biology+center+personnel/Quantum+biology+center+personnel_mid.jpg",
        supporting_pic_2: "https://www.dtu.dk/english/-/media/dtudk/nyheder/webnyheder/2022/11/13884_dtu-danchip-800px_web.jpg?rw=960&rh=0&hash=9D8256B283579D5C03EFD84B3A788F7CADFEC314",
        supporting_pic_3: "https://science.ku.dk/forskning/kvanteforskning-paa-science/billedinformation/Pix_2_1100x600.jpg",
	},
]