import { Country } from './country';
import {ResearchStatus} from './status-enum';
export const COUNTRIES: Country[] = [
	{
        id: 1,
        title: "Easy crop distribution",
        name: 'France',
		flag: 'c/c3/Flag_of_France.svg',
		area: 640679,
		population: 64979548,
        short_desc: "This project is expected to improve the availability of crops on market.",
        big_desc:"Easy crop distribution projects are initiatives that aim to streamline the process of distributing crops from farmers to consumers. These projects involve the use of modern technologies and best practices to improve the efficiency and transparency of crop distribution. They may include activities such as creating online marketplaces, implementing digital payment systems, and using data analytics to forecast demand and manage inventory. Easy crop distribution projects may also involve the creation of transportation and logistics networks to ensure that crops are delivered quickly and efficiently. The goal of these projects is to reduce waste, increase profitability for farmers, and provide consumers with access to fresh and affordable produce. By improving the efficiency of crop distribution, these projects can also contribute to economic growth and development at the local and national level.",
        category: "Agriculture",
        status:ResearchStatus.Ongoing,
        owner:"Joanna Keza",
        cover_pic: "https://sustainableagriculture.net/wp-content/uploads/2018/09/Farmers-Market-credit-Lindsey-Scalera-e1537458398168.png",
        supporting_pic_1: "https://d3kqdc25i4tl0t.cloudfront.net/articles/content/497_449074_management.hero.jpg",
        supporting_pic_2: "https://www.foodnavigator-asia.com/var/wrbm_gb_food_pharma/storage/images/publications/food-beverage-nutrition/foodnavigator-asia.com/headlines/processing-packaging/high-value-veg-new-philippines-processing-facility-to-transform-crops-to-profitable-products/11524912-1-eng-GB/High-value-veg-New-Philippines-processing-facility-to-transform-crops-to-profitable-products.jpg",
        supporting_pic_3: "https://science.ku.dk/forskning/kvanteforskning-paa-science/billedinformation/Pix_2_1100x600.jpg",
	},

    {
        id: 2,
        title: "Waste-based energy",
        name: 'Germany',
		flag: 'b/ba/Flag_of_Germany.svg',
		area: 357114,
        population: 36624199,
        short_desc: "This research is expected to generate new form of energy from waste.",
        big_desc:"Waste-based energy projects are initiatives that aim to generate electricity or heat from various waste streams. These projects involve the use of advanced technologies to convert waste materials such as municipal solid waste, agricultural waste, industrial waste, and sewage sludge into usable forms of energy. The process typically involves sorting, processing, and converting the waste into a fuel source that can be burned to produce energy. Waste-based energy projects are important because they offer a sustainable solution for waste disposal, reduce greenhouse gas emissions, and provide a renewable source of energy. The primary goal of these projects is to create a circular economy where waste is treated as a valuable resource and used to generate energy, reducing the dependence on fossil fuels.",
        category: "Research",
        status:ResearchStatus.Completed,
        owner:"John Kamana",
        cover_pic: "https://cdn.catf.us/wp-content/uploads/2022/09/03152954/GettyImages-1300144187-1-1400x934.jpg",
        supporting_pic_1: "https://d3kqdc25i4tl0t.cloudfront.net/articles/content/497_449074_management.hero.jpg",
        supporting_pic_2: "https://www.dtu.dk/english/-/media/dtudk/nyheder/webnyheder/2022/11/13884_dtu-danchip-800px_web.jpg?rw=960&rh=0&hash=9D8256B283579D5C03EFD84B3A788F7CADFEC314",
        supporting_pic_3: "https://science.ku.dk/forskning/kvanteforskning-paa-science/billedinformation/Pix_2_1100x600.jpg",
	},

    {
        id: 3,
        title: "E-learning platform",
        name: 'Canada',
		flag: 'c/cf/Flag_of_Canada.svg',
		area: 9976140,
		population: 36624199,
        short_desc: "This project is intended to implement an e-learning platform.",
        big_desc:"E-learning platform projects are online platforms that facilitate learning through digital resources such as video lectures, quizzes, and interactive exercises. These platforms offer a wide range of courses, from academic subjects to vocational training and personal development. They can be accessed from anywhere with an internet connection and offer flexible learning schedules, making education more accessible to people of all ages and backgrounds. E-learning platform projects are designed to provide a personalized and engaging learning experience, using algorithms to track progress and provide feedback. They also often incorporate social features such as discussion forums and peer-to-peer learning to foster a sense of community among learners. The goal of e-learning platform projects is to democratize education and provide people with the knowledge and skills they need to succeed in a rapidly changing world.",
        category: "Technology",
        status:ResearchStatus.Published,
        owner:"Jennifer Keza",
        cover_pic: "https://elearning.reb.rw/pluginfile.php/158/coursecat/description/DSC_7377.JPG",
        supporting_pic_1: "https://d3kqdc25i4tl0t.cloudfront.net/articles/content/497_449074_management.hero.jpg",
        supporting_pic_2: "https://www.scienceabc.com/wp-content/uploads/2020/07/Our-planet-earth-and-its-diverse-ecosystems.jpg",
        supporting_pic_3: "https://science.ku.dk/forskning/kvanteforskning-paa-science/billedinformation/Pix_2_1100x600.jpg",
	},

    {
        id: 4,
        title: "Passenger queue management",
        name: 'Vietnam',
		flag: '2/21/Flag_of_Vietnam.svg',
		area: 331212,
		population: 95540800,
        short_desc: "Addressing passengers queue problems is our main goals",
        big_desc:"Passenger queue management projects are initiatives that aim to improve the flow of passengers in transportation hubs such as airports, train stations, and bus terminals. These projects involve the use of technology to manage queues, providing real-time information to passengers and staff. They typically use sensors and analytics to monitor passenger flow and provide alerts to staff when queues become congested. Passenger queue management projects may also use digital signage to display estimated waiting times and direct passengers to the correct queues. The goal of these projects is to improve the passenger experience by reducing wait times and providing a more efficient and organized system for managing queues, while also improving the operational efficiency of transportation hubs.",
        category: "Transport",
        status:ResearchStatus.Ongoing,
        owner:"Marc Izere",
        cover_pic: "https://en.igihe.com/IMG/arton46240.jpg?1658927480",
        supporting_pic_1: "https://d3kqdc25i4tl0t.cloudfront.net/articles/content/497_449074_management.hero.jpg",
        supporting_pic_2: "https://www.scienceabc.com/wp-content/uploads/2020/07/Our-planet-earth-and-its-diverse-ecosystems.jpg",
        supporting_pic_3: "https://science.ku.dk/forskning/kvanteforskning-paa-science/billedinformation/Pix_2_1100x600.jpg",
	},

    {
        id: 5,
        title: "Tourist Guider",
        name: 'Brazil',
		flag: '0/05/Flag_of_Brazil.svg',
		area: 8515767,
		population: 209288278,
        short_desc: "This project will aim to help and guide tourists.",
        big_desc:"Tourist guider projects are initiatives that aim to enhance the experience of travelers by providing expert guidance and local knowledge. These projects involve trained guides who accompany tourists on their journeys and provide information about the history, culture, and attractions of the destination. Tourist guider projects may involve a range of activities, including city tours, hiking expeditions, and cultural events. They may also offer personalized itineraries and recommendations based on the interests of individual travelers. The goal of these projects is to provide a unique and enriching travel experience, while also supporting the local economy by promoting tourism and highlighting the cultural and natural resources of the destination.",
        category: "Technology",
        status:ResearchStatus.Review,
        owner:"Jacky Reba",
        cover_pic: "https://www.globaltourismforum.org/wp-content/uploads/2020/02/travel-scaled.jpg",
        supporting_pic_1: "https://d3kqdc25i4tl0t.cloudfront.net/articles/content/497_449074_management.hero.jpg",
        supporting_pic_2: "https://www.scienceabc.com/wp-content/uploads/2020/07/Our-planet-earth-and-its-diverse-ecosystems.jpg",
        supporting_pic_3: "https://science.ku.dk/forskning/kvanteforskning-paa-science/billedinformation/Pix_2_1100x600.jpg",
	},

    {
        id: 6,
        title: "Boosting Agri-production",
        name: 'Mexico',
		flag: 'f/fc/Flag_of_Mexico.svg',
		area: 1964375,
		population: 129163276,
        short_desc: "This project is intended to improve agriculture production.",
        big_desc:"Boosting agri-production projects are initiatives that aim to increase the productivity and profitability of agricultural activities. These projects involve the use of modern technologies and best practices to improve crop yields, reduce waste, and increase efficiency. They may include activities such as soil analysis, crop rotation, irrigation systems, and pest management. Boosting agri-production projects may also provide training and education to farmers to help them adopt new techniques and technologies. The goal of these projects is to increase food security, reduce poverty, and improve the livelihoods of farmers and rural communities. By improving the productivity and profitability of agriculture, these projects can also contribute to economic growth and development at the national level.",
        category: "Agriculture",
        status:ResearchStatus.Completed,
        owner:"Chris Berwa",
        cover_pic: "https://www.un.org/africarenewal/sites/www.un.org.africarenewal/files/styles/ar_main_story_big_picture/public/images/kenyan-farmer.jpg?itok=Akub4WSN",
        supporting_pic_1: "https://d3kqdc25i4tl0t.cloudfront.net/articles/content/497_449074_management.hero.jpg",
        supporting_pic_2: "https://www.scienceabc.com/wp-content/uploads/2020/07/Our-planet-earth-and-its-diverse-ecosystems.jpg",
        supporting_pic_3: "https://science.ku.dk/forskning/kvanteforskning-paa-science/billedinformation/Pix_2_1100x600.jpg",
	},

    {
        id: 7,
        title: "Culture promotion",
        name: 'United States',
		flag: 'a/a4/Flag_of_the_United_States.svg',
		area: 9629091,
		population: 324459463,
        short_desc: "The main intention of this project is to promote Rwandan Culture",
       big_desc:"Culture promotion projects are initiatives that aim to preserve and promote the cultural heritage of a particular community or region. These projects involve a range of activities, such as organizing cultural events and festivals, preserving historical artifacts and buildings, and promoting traditional arts and crafts. Culture promotion projects may also involve the creation of cultural tourism programs, which highlight the unique cultural traditions of a particular area and encourage tourism. The goal of these projects is to foster a sense of pride and identity among members of the community, while also preserving cultural heritage for future generations. By promoting cultural tourism, these projects can also generate economic benefits for the community, such as increased revenue from tourism-related activities.",
        category: "Society",
        status:ResearchStatus.Recruiting,
        owner:"Ange Mahoro",
        cover_pic: "https://i.natgeofe.com/n/51dc8240-a2ba-4ea7-bd53-b7dae0d97fbd/intore-dancers-performance-visit-rwanda.jpg",
        supporting_pic_1: "https://d3kqdc25i4tl0t.cloudfront.net/articles/content/497_449074_management.hero.jpg",
        supporting_pic_2: "https://www.scienceabc.com/wp-content/uploads/2020/07/Our-planet-earth-and-its-diverse-ecosystems.jpg",
        supporting_pic_3: "https://science.ku.dk/forskning/kvanteforskning-paa-science/billedinformation/Pix_2_1100x600.jpg",
	},

    {
        id: 8,
        title: "Environment preservation",
        name: 'India',
		flag: '4/41/Flag_of_India.svg',
		area: 3287263,
		population: 1324171354,
        short_desc: "This project is intended to preserve environment",
        big_desc:"Environment preservation projects are initiatives that aim to protect and conserve natural resources and ecosystems. These projects involve a range of activities, such as habitat restoration, waste reduction and recycling, and the promotion of sustainable practices. Environment preservation projects may also involve the creation of protected areas, such as national parks and nature reserves, to preserve biodiversity and protect endangered species. The goal of these projects is to reduce the negative impact of human activities on the environment, promote sustainable development, and ensure the long-term survival of natural resources and ecosystems. By preserving the environment, these projects can also contribute to human well-being by providing essential services such as clean water, clean air, and food security.",
        category: "Ecosystem",
        status:ResearchStatus.Completed,
        owner:"Tom Mucyo",
        cover_pic: "https://eige.europa.eu/sites/default/files/styles/eige_original_optimised/public/images/environment_climate_change_0.jpg?itok=OgfBMStR",
        supporting_pic_1: "https://d3kqdc25i4tl0t.cloudfront.net/articles/content/497_449074_management.hero.jpg",
        supporting_pic_2: "https://www.scienceabc.com/wp-content/uploads/2020/07/Our-planet-earth-and-its-diverse-ecosystems.jpg",
        supporting_pic_3: "https://science.ku.dk/forskning/kvanteforskning-paa-science/billedinformation/Pix_2_1100x600.jpg",
	},

    {
        id: 9,
        title: "Linking houses with clients",
        name: 'Indonesia',
		flag: '9/9f/Flag_of_Indonesia.svg',
		area: 1910931,
		population: 263991379,
        short_desc: "This project is intended to change house renting process.",
        big_desc:"Linking houses with clients projects are initiatives that aim to connect homeowners with potential buyers or renters of their properties. These projects involve the use of online platforms and other marketing strategies to promote properties to a wider audience. They may also provide tools such as virtual tours and property assessments to help clients make informed decisions about their potential purchases or rentals. Linking houses with clients projects may also offer additional services such as legal assistance, property management, and financial advice. The goal of these projects is to facilitate a smooth and efficient process for buying or renting a home, while also providing support and guidance to clients throughout the process. By connecting homeowners with potential buyers or renters, these projects can also contribute to economic growth and development in the real estate sector.",
        category: "Trading",
        status:ResearchStatus.Review,
        owner:"Peter Tuyizere",
        cover_pic: "https://www.houseinrwanda.com/sites/default/files/inline-images/xna4.jpg.pagespeed.ic.nCCvZ96eon.jpg",
        supporting_pic_1: "https://d3kqdc25i4tl0t.cloudfront.net/articles/content/497_449074_management.hero.jpg",
        supporting_pic_2: "https://www.scienceabc.com/wp-content/uploads/2020/07/Our-planet-earth-and-its-diverse-ecosystems.jpg",
        supporting_pic_3: "https://science.ku.dk/forskning/kvanteforskning-paa-science/billedinformation/Pix_2_1100x600.jpg",
	},

    {
        id: 10,
        title: "Bringing back street children to normal life",
        name: 'Tuvalu',
		flag: '3/38/Flag_of_Tuvalu.svg',
		area: 26,
		population: 11097,
        short_desc: "This project is intended to help street children",
        big_desc:"Bringing back street children to normal life projects are initiatives that aim to provide support and assistance to children who are living on the streets. These projects involve a range of activities, such as outreach programs, counseling and rehabilitation services, education and skills training, and reintegration into family and community life. Bringing back street children to normal life projects may also provide basic necessities such as food, shelter, and healthcare. The goal of these projects is to protect the rights and well-being of children living on the streets, provide them with opportunities to improve their lives, and ultimately help them transition back into mainstream society. By providing support and assistance to street children, these projects can also contribute to social and economic development by reducing poverty and promoting education and employment opportunities.",
        category: "Society",
        status:ResearchStatus.Ongoing,
        owner:"Joy Karabo",
        cover_pic: "https://rightscorridor.com/wp-content/uploads/2020/02/Street-children-in-Nyabugogo-a-Kigali-city-suburb.-File-photo-The-New-Times-2.jpg",
        supporting_pic_1: "https://d3kqdc25i4tl0t.cloudfront.net/articles/content/497_449074_management.hero.jpg",
        supporting_pic_2: "https://www.scienceabc.com/wp-content/uploads/2020/07/Our-planet-earth-and-its-diverse-ecosystems.jpg",
        supporting_pic_3: "https://science.ku.dk/forskning/kvanteforskning-paa-science/billedinformation/Pix_2_1100x600.jpg",
	},

    {
        id: 11,
        title: "Easy crop distribution",
        name: 'France',
		flag: 'c/c3/Flag_of_France.svg',
		area: 640679,
		population: 64979548,
        short_desc: "This project is expected to improve the availability of crops on market.",
        big_desc:"Easy crop distribution projects are initiatives that aim to streamline the process of distributing crops from farmers to consumers. These projects involve the use of modern technologies and best practices to improve the efficiency and transparency of crop distribution. They may include activities such as creating online marketplaces, implementing digital payment systems, and using data analytics to forecast demand and manage inventory. Easy crop distribution projects may also involve the creation of transportation and logistics networks to ensure that crops are delivered quickly and efficiently. The goal of these projects is to reduce waste, increase profitability for farmers, and provide consumers with access to fresh and affordable produce. By improving the efficiency of crop distribution, these projects can also contribute to economic growth and development at the local and national level.",
        category: "Trading",
        status:ResearchStatus.Ongoing,
        owner:"Peter Tuyizere",
        cover_pic: "https://sustainableagriculture.net/wp-content/uploads/2018/09/Farmers-Market-credit-Lindsey-Scalera-e1537458398168.png",
        supporting_pic_1: "https://d3kqdc25i4tl0t.cloudfront.net/articles/content/497_449074_management.hero.jpg",
        supporting_pic_2: "https://www.scienceabc.com/wp-content/uploads/2020/07/Our-planet-earth-and-its-diverse-ecosystems.jpg",
        supporting_pic_3: "https://science.ku.dk/forskning/kvanteforskning-paa-science/billedinformation/Pix_2_1100x600.jpg",
	},

    {
        id: 12,
        title: "Waste-based energy",
        name: 'Germany',
		flag: 'b/ba/Flag_of_Germany.svg',
		area: 357114,
        population: 36624199,
        short_desc: "This research is expected to generate new form of energy from waste.",
        big_desc:"Waste-based energy projects are initiatives that aim to generate electricity or heat from various waste streams. These projects involve the use of advanced technologies to convert waste materials such as municipal solid waste, agricultural waste, industrial waste, and sewage sludge into usable forms of energy. The process typically involves sorting, processing, and converting the waste into a fuel source that can be burned to produce energy. Waste-based energy projects are important because they offer a sustainable solution for waste disposal, reduce greenhouse gas emissions, and provide a renewable source of energy. The primary goal of these projects is to create a circular economy where waste is treated as a valuable resource and used to generate energy, reducing the dependence on fossil fuels.",
        category: "Research",
        status:ResearchStatus.Completed,
        owner:"John Kamana",
        cover_pic: "https://cdn.catf.us/wp-content/uploads/2022/09/03152954/GettyImages-1300144187-1-1400x934.jpg",
        supporting_pic_1: "https://d3kqdc25i4tl0t.cloudfront.net/articles/content/497_449074_management.hero.jpg",
        supporting_pic_2: "https://www.scienceabc.com/wp-content/uploads/2020/07/Our-planet-earth-and-its-diverse-ecosystems.jpg",
        supporting_pic_3: "https://science.ku.dk/forskning/kvanteforskning-paa-science/billedinformation/Pix_2_1100x600.jpg",
	},

    {
        id: 13,
        title: "E-learning platform",
        name: 'Canada',
		flag: 'c/cf/Flag_of_Canada.svg',
		area: 9976140,
		population: 36624199,
        short_desc: "This project is intended to implement an e-learning platform.",
        big_desc:"E-learning platform projects are online platforms that facilitate learning through digital resources such as video lectures, quizzes, and interactive exercises. These platforms offer a wide range of courses, from academic subjects to vocational training and personal development. They can be accessed from anywhere with an internet connection and offer flexible learning schedules, making education more accessible to people of all ages and backgrounds. E-learning platform projects are designed to provide a personalized and engaging learning experience, using algorithms to track progress and provide feedback. They also often incorporate social features such as discussion forums and peer-to-peer learning to foster a sense of community among learners. The goal of e-learning platform projects is to democratize education and provide people with the knowledge and skills they need to succeed in a rapidly changing world.",
        category: "Education",
        status:ResearchStatus.Published,
        owner:"Hanna Mucyo",
        cover_pic: "https://elearning.reb.rw/pluginfile.php/158/coursecat/description/DSC_7377.JPG",
        supporting_pic_1: "https://d3kqdc25i4tl0t.cloudfront.net/articles/content/497_449074_management.hero.jpg",
        supporting_pic_2: "https://www.scienceabc.com/wp-content/uploads/2020/07/Our-planet-earth-and-its-diverse-ecosystems.jpg",
        supporting_pic_3: "https://science.ku.dk/forskning/kvanteforskning-paa-science/billedinformation/Pix_2_1100x600.jpg",
	},
]